### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda'

### ISSUE THREAD

**Issue by dzyjjpy** [lxy5513/hrnet#13]
When I run:  python video.py, errors occured. **ImportError: cannot import name 'deform_conv_cuda'**
Someone suggest reinstall pytorch==1.0.1, 
I try but it dosen't work. @lxy5513 Do you have any  suggestion?
error displays as below:
/home/jiapy/virtualEnv/py3torch4HRNet/bin/python3.6 /home/jiapy/workspace/hrnet/pose_estimation/video.py -i ./right-2-out.mp4 -o /output/output.mp4 --display
/home/jiapy/virtualEnv/py3torch4HRNet/lib/python3.6/site-packages/IPython/core/interactiveshell.py:931: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
Traceback (most recent call last):
  File "/home/jiapy/workspace/hrnet/pose_estimation/video.py", line 29, in <module>
    from lib.detector.mmdetection.high_api import human_boxes_get as mm_det
  File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/high_api.py", line 8, in <module>
    from mmdet.models import build_detector
  File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/models/backbones/__init__.py", line 1, in <module>
    from .resnet import ResNet, make_res_layer
  File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/models/backbones/resnet.py", line 9, in <module>
    from mmdet.ops import DeformConv, ModulatedDeformConv
  File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/ops/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File **"/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from .. import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'**

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by YinXiaojieCSDN** [comment]
> When I run: python video.py, errors occured. **ImportError: cannot import name 'deform_conv_cuda'**
> Someone suggest reinstall pytorch==1.0.1,
> I try but it dosen't work. @lxy5513 Do you have any suggestion?
> error displays as below:
> /home/jiapy/virtualEnv/py3torch4HRNet/bin/python3.6 /home/jiapy/workspace/hrnet/pose_estimation/video.py -i ./right-2-out.mp4 -o /output/output.mp4 --display
> /home/jiapy/virtualEnv/py3torch4HRNet/lib/python3.6/site-packages/IPython/core/interactiveshell.py:931: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
> warn("Attempting to work in a virtualenv. If you encounter problems, please "
> Traceback (most recent call last):
> File "/home/jiapy/workspace/hrnet/pose_estimation/video.py", line 29, in
> from lib.detector.mmdetection.high_api import human_boxes_get as mm_det
> File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/high_api.py", line 8, in
> from mmdet.models import build_detector
> File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/models/**init**.py", line 1, in
> from .backbones import * # noqa: F401,F403
> File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/models/backbones/**init**.py", line 1, in
> from .resnet import ResNet, make_res_layer
> File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/models/backbones/resnet.py", line 9, in
> from mmdet.ops import DeformConv, ModulatedDeformConv
> File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/ops/**init**.py", line 1, in
> from .dcn import (DeformConv, DeformConvPack, ModulatedDeformConv,
> File "/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/ops/dcn/**init**.py", line 1, in
> from .functions.deform_conv import deform_conv, modulated_deform_conv
> File **"/home/jiapy/workspace/hrnet/lib/detector/mmdetection/mmd/mmdet/ops/dcn/functions/deform_conv.py", line 5, in from .. import deform_conv_cuda ImportError: cannot import name 'deform_conv_cuda'**
> 
> If you suspect this is an IPython bug, please report it at:
> https://github.com/ipython/ipython/issues
> or send an email to the mailing list at [ipython-dev@python.org](mailto:ipython-dev@python.org)
> 
> You can print a more detailed traceback right now with "%tb", or use "%debug"
> to interactively debug it.
> 
> Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
> %config Application.verbose_crash=True

you can reference http://blog.leanote.com/post/liuliu408/5.
